### PR TITLE
Add command support

### LINKED ISSUE #4: Code for SSH Session on Linux without a terminal
https://github.com/Fahrj/reverse-ssh/blob/master/ssh_session_unix.go#L58-L61

This code seems to be forgotten as we did the copy/pasta from the gliderlabs example. What should we do in this case? Error out?

### PR DESCRIPTION
**Pull request by Fahrj**
This PR will implement command support for Linux systems, e.g. for scp

Examples:
```
scp target:/etc/passwd passwd
ssh target whoami
```

Closes #4

### CODE REVIEW

**Comment by Fahrj** [comment]
@rumpelsepp does that work for you?

**Comment by rumpelsepp** [comment]
Commands work, `scp -p 8888 /etc/passwd localhost:` hangs. It copies the file successfully, but `scp` does not terminate. Currently no time to investigate.

**Comment by Fahrj** [comment]
> Commands work, `scp -p 8888 /etc/passwd localhost:` hangs.

Good catch! Interestingly enough it works the other way around, for `scp -p 8888 localhost:/etc/passwd .`

**Comment by Fahrj** [comment]
I could locate the bug: `scp -p 8888 /etc/passwd localhost:` finishes with sending `EOF`, which results in `io.Copy` to return. This resulted in the remote `scp` process to hang, because it waited for `stdInPipe` to be closed and never returned. [This code block](https://github.com/Fahrj/reverse-ssh/pull/7/commits/a889321f8bfac49969cb14b0c5c5a8a4a062e78f#diff-7bbe2bda106647be0206dde59d46cad8e3d99140e4bb780cc07979be66961801L47-R55) contains the fix, but I went ahead and also added a little process management in case the client closes connections (detectable via `s.Context().Done()`).

**Comment by rumpelsepp** [comment]
I tested it and `scp` works now in both directions. The had a short look at the error handling code; looks fine IMO.

**Comment by rumpelsepp** [comment]
Ship it!

**Pull request merged**
